/**
 * Amersfoort — municipal layers discovered 2026-05-08.
 *
 * Source: Gemeente Amersfoort ArcGIS Online
 *   https://amersfoort.maps.arcgis.com (org: xJqVgvX1Tdd3h0YB)
 *   https://services-eu1.arcgis.com/xJqVgvX1Tdd3h0YB/arcgis/rest/services
 *
 * Auto-generated by /promote-city; review before commit.
 *
 * 1 live city layer. Provincial Utrecht layers (ut-prov-*) are injected
 * separately via PROVINCIAL_BUILDERS["Utrecht"].
 *
 * Note: Amersfoort's ArcGIS org has very limited public exposure (1 public
 * FeatureService found). The kaart.amersfoort.nl viewer appears internally
 * hosted and does not expose a public REST endpoint.
 */

import type { CityConfig } from "../../cities";
import type { DataSource } from "../types";
import { fetchArcGISQuery } from "../fetchers";

const AMERSFOORT_GIS =
  "https://services-eu1.arcgis.com/xJqVgvX1Tdd3h0YB/arcgis/rest/services";

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function buildAmersfoortLayers(_city: CityConfig): DataSource[] {
  return [
    // ─── GROEN & ECOLOGIE ─────────────────────────────────────────────────────
    {
      id: "amf-snoeproutes",
      name: "Snoeiroutes",
      description:
        "Gemeentelijke snoeiroutes per buurt in Amersfoort — routes voor periodiek onderhoud van bomen en beplanting.",
      source: "Gemeente Amersfoort GIS",
      sourceUrl:
        "https://services-eu1.arcgis.com/xJqVgvX1Tdd3h0YB/arcgis/rest/services/Snoeproutes/FeatureServer",
      endpoint:
        "services-eu1.arcgis.com/xJqVgvX1Tdd3h0YB/arcgis/rest/services/Snoeproutes/FeatureServer/0",
      category: "groen-ecologie",
      color: [34, 160, 80, 200],
      icon: "TreePine",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 500,
      fetchData: async (full) =>
        fetchArcGISQuery(AMERSFOORT_GIS, "Snoeproutes", 0, "FeatureServer", 500, full),
    },
  ];
}
