/**
 * Elburg — municipal layers discovered 2026-05-09.
 *
 * Source: services-eu1.arcgis.com/l6Drc1A04T0QsiNl (Gemeente Elburg ArcGIS Online)
 *
 * Gemeente Elburg publiceert openbare GIS-data via een eigen ArcGIS Online
 * organisatie (owner: jan.pieter.den.boer@elburg.nl_gemeente_elburg en
 * wim.van.den.bos@elburg.nl_gemeente_elburg). Lagen zijn gevonden via een
 * ArcGIS Online search op tag "Elburg" en bevestigd live op 2026-05-09.
 *
 * Elburg is een kleine historische gemeente (~23k inwoners) op de Noord-Veluwe
 * in Gelderland, met het goed bewaarde vestingstadje als kernattractie.
 *
 * Auto-generated by /promote-city; review before commit.
 */

import type { CityConfig } from "../../cities";
import type { DataSource } from "../types";
import { fetchArcGISPaged } from "../fetchers";

const GEM = "https://services-eu1.arcgis.com/l6Drc1A04T0QsiNl/arcgis/rest/services";

function fetchElburg(
  service: string,
  layerId: number,
  maxFeatures = 2000,
  full?: boolean
): Promise<GeoJSON.FeatureCollection> {
  const queryUrl = `${GEM}/${service}/FeatureServer/${layerId}/query?where=1%3D1&outFields=*&outSR=4326&f=geojson`;
  return fetchArcGISPaged(queryUrl, maxFeatures, full ?? false);
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function buildElburgLayers(_city: CityConfig): DataSource[] {
  return [
    // ═══════════════════════════════════════
    // BODEM & ONDERGROND (BOG)
    // ═══════════════════════════════════════
    {
      id: "elb-rioolstrengen",
      name: "Rioolstrengen (rioolnet)",
      description:
        "Rioolstrengen (lijnen) van het gemeentelijke rioolstelsel in Elburg — met streng­naam, aanlegjaar en BOB-hoogtes (binnenonderkant buis begin/eind) als ondergrondse leidinginformatie.",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/Rioolhuisaansluiting3/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/Rioolhuisaansluiting3/FeatureServer/5",
      category: "bodem-ondergrond",
      bog: true,
      isNew: true,
      color: [110, 90, 200, 200],
      icon: "Pipette",
      visible: false,
      loading: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: (full) => fetchElburg("Rioolhuisaansluiting3", 5, 2000, full),
    },
    {
      id: "elb-rioolputten",
      name: "Rioolputten",
      description:
        "Rioolputten (inspectieputten/kolken) in de gemeente Elburg met putnummer, soort put, aanlegjaar en maaiveldhoogte — kernobjecten van de ondergrondse riolering.",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/Rioolhuisaansluiting3/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/Rioolhuisaansluiting3/FeatureServer/6",
      category: "bodem-ondergrond",
      bog: true,
      isNew: true,
      color: [90, 70, 160, 220],
      icon: "CircleDot",
      visible: false,
      loading: false,
      pointType: "circle",
      radius: 3,
      defaultLimit: 2000,
      fetchData: (full) => fetchElburg("Rioolhuisaansluiting3", 6, 2000, full),
    },
    {
      id: "elb-rioolconstructie-lijnen",
      name: "Rioolconstructie (lijnen)",
      description:
        "Constructie-elementen van de riolering als lijnen (type-geclassificeerd) in de gemeente Elburg — onderdeel van de ondergrondse rioolinfrastructuur.",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/Rioolhuisaansluiting3/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/Rioolhuisaansluiting3/FeatureServer/7",
      category: "bodem-ondergrond",
      bog: true,
      isNew: true,
      color: [70, 60, 130, 200],
      icon: "Pipette",
      visible: false,
      loading: false,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: (full) => fetchElburg("Rioolhuisaansluiting3", 7, 2000, full),
    },
    {
      id: "elb-rioolconstructie-vlakken",
      name: "Rioolconstructie (vlakken)",
      description:
        "Rioolconstructie-vlakken (type-geclassificeerde polygonen) uit de rioolkaart van de gemeente Elburg — ondergrondse constructie-onderdelen van het rioolstelsel.",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/rioolkaart_rioolconstructie/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/rioolkaart_rioolconstructie/FeatureServer/0",
      category: "bodem-ondergrond",
      bog: true,
      isNew: true,
      color: [120, 100, 180, 170],
      icon: "Layers",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) =>
        fetchElburg("rioolkaart_rioolconstructie", 0, 2000, full),
    },

    // ═══════════════════════════════════════
    // GEBOUWEN & INFRA
    // ═══════════════════════════════════════
    {
      id: "elb-gemeentelijke-monumenten",
      name: "Gemeentelijke monumenten",
      description:
        "Gemeentelijk beschermde monumenten in Elburg als polygonen — inclusief de historische vesting en grachtengordel.",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/Gem_monumenten_weergave/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/Gem_monumenten_weergave/FeatureServer/0",
      category: "gebouwen-infra",
      color: [180, 130, 60, 200],
      icon: "Landmark",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) => fetchElburg("Gem_monumenten_weergave", 0, 2000, full),
    },
    {
      id: "elb-rijksmonumenten",
      name: "Rijksmonumenten (erfgoedkaart)",
      description:
        "Rijksmonumenten in Elburg weergegeven als polygonen (erfgoedkaart — inclusief Vesting Elburg-complex).",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/Erfgoedkaart_Rijksmonumenten_weergave/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/Erfgoedkaart_Rijksmonumenten_weergave/FeatureServer/0",
      category: "gebouwen-infra",
      color: [220, 100, 60, 200],
      icon: "Landmark",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) =>
        fetchElburg("Erfgoedkaart_Rijksmonumenten_weergave", 0, 2000, full),
    },
    {
      id: "elb-rioolhuisaansluiting",
      name: "Rioolhuisaansluitingen",
      description:
        "Ligging van de rioolhuisaansluitingen (DWA/HWA) in de gemeente Elburg.",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/Rioolhuisaansluiting3/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/Rioolhuisaansluiting3/FeatureServer/0",
      category: "gebouwen-infra",
      color: [80, 120, 200, 180],
      icon: "Pipette",
      visible: false,
      loading: false,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: (full) => fetchElburg("Rioolhuisaansluiting3", 0, 2000, full),
    },
    {
      id: "elb-openbare-verlichting",
      name: "Openbare verlichting — lichtmasten",
      description:
        "Lichtmasten van de openbare verlichting in de gemeente Elburg (registratie 2024).",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/2024_OV_Gemeente_Elburg_WFL1/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/2024_OV_Gemeente_Elburg_WFL1/FeatureServer/1",
      category: "gebouwen-infra",
      color: [240, 200, 60, 220],
      icon: "Lightbulb",
      visible: false,
      loading: false,
      pointType: "circle",
      radius: 3,
      defaultLimit: 2000,
      fetchData: (full) =>
        fetchElburg("2024_OV_Gemeente_Elburg_WFL1", 1, 2000, full),
    },
    {
      id: "elb-ov-kasten",
      name: "Openbare verlichting — kasten",
      description:
        "Schakelkasten voor openbare verlichting in de gemeente Elburg (registratie 2024).",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/2024_OV_Gemeente_Elburg_WFL1/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/2024_OV_Gemeente_Elburg_WFL1/FeatureServer/0",
      category: "gebouwen-infra",
      color: [200, 160, 50, 200],
      icon: "Zap",
      visible: false,
      loading: false,
      pointType: "circle",
      radius: 4,
      defaultLimit: 2000,
      fetchData: (full) =>
        fetchElburg("2024_OV_Gemeente_Elburg_WFL1", 0, 2000, full),
    },

    // ═══════════════════════════════════════
    // GROEN & ECOLOGIE
    // ═══════════════════════════════════════
    {
      id: "elb-boomzone",
      name: "Boomzones en boomstructuren",
      description:
        "Boomstructuren en boomzones (lijnvormige groenelementen) in het beheergebied van de gemeente Elburg.",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/boomzone/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/boomzone/FeatureServer/0",
      category: "groen-ecologie",
      color: [40, 160, 80, 180],
      icon: "TreePine",
      visible: false,
      loading: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: (full) => fetchElburg("boomzone", 0, 2000, full),
    },
    {
      id: "elb-speelplaatsen",
      name: "Speelplaatsen en sportfaciliteiten",
      description:
        "Speelplaatsen, sportterreinen en buitensportfaciliteiten (o.a. basketbalveld) in de gemeente Elburg.",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/speel/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/speel/FeatureServer/0",
      category: "groen-ecologie",
      color: [80, 200, 120, 220],
      icon: "Dumbbell",
      visible: false,
      loading: false,
      pointType: "circle",
      radius: 5,
      defaultLimit: 2000,
      fetchData: (full) => fetchElburg("speel", 0, 2000, full),
    },
    {
      id: "elb-bladkorven",
      name: "Bladkorven",
      description:
        "Locaties van bladkorven (bladvangbakken) in de openbare ruimte van de gemeente Elburg.",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/Badkorf_point_WFL1/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/Badkorf_point_WFL1/FeatureServer/0",
      category: "groen-ecologie",
      color: [160, 120, 60, 200],
      icon: "Leaf",
      visible: false,
      loading: false,
      pointType: "circle",
      radius: 4,
      defaultLimit: 2000,
      fetchData: (full) => fetchElburg("Badkorf_point_WFL1", 0, 2000, full),
    },

    // ═══════════════════════════════════════
    // VERKEER & LOGISTIEK
    // ═══════════════════════════════════════
    {
      id: "elb-parkeren",
      name: "Parkeergebieden",
      description:
        "Parkeergebieden in de binnenstad en het centrum van Elburg — inclusief voetgangerszones en beperkt toegankelijke zones.",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/Parkeren/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/Parkeren/FeatureServer/0",
      category: "verkeer-logistiek",
      color: [60, 120, 220, 160],
      icon: "ParkingSquare",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) => fetchElburg("Parkeren", 0, 2000, full),
    },
    {
      id: "elb-strooiroute",
      name: "Strooiroutes (winterdienst)",
      description:
        "Rijroutes voor zout- en zandstrooiers bij gladheidbestrijding in de gemeente Elburg.",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/Strooiroute_gemeente_Elburg/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/Strooiroute_gemeente_Elburg/FeatureServer/0",
      category: "verkeer-logistiek",
      color: [200, 160, 60, 200],
      icon: "Snowflake",
      visible: false,
      loading: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: (full) =>
        fetchElburg("Strooiroute_gemeente_Elburg", 0, 2000, full),
    },

    // ═══════════════════════════════════════
    // MOBILITEITSDIENSTEN
    // ═══════════════════════════════════════
    {
      id: "elb-ligplaatsen",
      name: "Ligplaatsen haven Elburg",
      description:
        "Genummerde ligplaatsen in de haven van Elburg — jachthaven en recreatieve watervaart.",
      source: "Gemeente Elburg GIS",
      sourceUrl: `${GEM}/Ligplaatsen/FeatureServer`,
      endpoint:
        "services-eu1.arcgis.com/l6Drc1A04T0QsiNl/…/Ligplaatsen/FeatureServer/0",
      category: "mobiliteitsdiensten",
      color: [60, 160, 220, 200],
      icon: "Anchor",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) => fetchElburg("Ligplaatsen", 0, 2000, full),
    },
  ];
}
