/**
 * Lochem — municipal layers discovered 2026-05-09.
 *
 * Source: services-eu1.arcgis.com/VV2g0JnRRF5xL5uh (Datalab Gelderland Oost — DLGO9)
 *         services-eu1.arcgis.com/7Hne9Ajbj36KaHMj (CirculusBeheer — beheerder publieke ruimte)
 *
 * DLGO9 ("Datalab Gelderland Oost 9") publiceert datasets voor 9 oost-Gelderse
 * gemeenten (waaronder Lochem). Voor lagen die DLGO9-breed zijn, intersecteert
 * de geometrie sowieso met Lochems bbox; we noemen ze in dit module dan ook
 * met een DLGO9-suffix om herkomst duidelijk te houden.
 *
 * Auto-generated by /promote-city; review before commit.
 */

import type { CityConfig } from "../../cities";
import type { DataSource } from "../types";
import { fetchArcGISPaged } from "../fetchers";

const DLGO = "https://services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/arcgis/rest/services";
const CIRC = "https://services-eu1.arcgis.com/7Hne9Ajbj36KaHMj/arcgis/rest/services";

function fetchDlgo(
  service: string,
  layerId: number,
  maxFeatures = 2000,
  full?: boolean
): Promise<GeoJSON.FeatureCollection> {
  const queryUrl = `${DLGO}/${service}/FeatureServer/${layerId}/query?where=1%3D1&outFields=*&outSR=4326&f=geojson`;
  return fetchArcGISPaged(queryUrl, maxFeatures, full ?? false);
}

/**
 * DLGO9-variant met een eigen `where`-clausule. Sommige DLGO9-brede lagen
 * (bodemkaart, grondwatertrappen) dragen een `statnaam`-veld per gemeente,
 * zodat we ze met `statnaam LIKE '%Lochem%'` precies tot Lochem kunnen
 * inperken in plaats van op bbox te vertrouwen.
 */
function fetchDlgoWhere(
  service: string,
  layerId: number,
  where: string,
  maxFeatures = 2000,
  full?: boolean
): Promise<GeoJSON.FeatureCollection> {
  const queryUrl = `${DLGO}/${service}/FeatureServer/${layerId}/query?where=${encodeURIComponent(
    where
  )}&outFields=*&outSR=4326&f=geojson`;
  return fetchArcGISPaged(queryUrl, maxFeatures, full ?? false);
}

function fetchCirc(
  service: string,
  layerId: number,
  maxFeatures = 2000,
  full?: boolean
): Promise<GeoJSON.FeatureCollection> {
  const queryUrl = `${CIRC}/${service}/FeatureServer/${layerId}/query?where=1%3D1&outFields=*&outSR=4326&f=geojson`;
  return fetchArcGISPaged(queryUrl, maxFeatures, full ?? false);
}

export function buildLochemLayers(_city: CityConfig): DataSource[] {
  return [
    // ═══════════════════════════════════════
    // BODEM & ONDERGROND (BOG)
    // ═══════════════════════════════════════
    {
      id: "lch-bodemkaart",
      name: "Bodemkaart (BRO)",
      description: "Bodemtypen en -opbouw in Lochem volgens de landelijke Bodemkaart (BRO), per gemeente ontsloten door Datalab Gelderland Oost. Toont grondsoort, bodemcode-omschrijving en kalkklasse per vlak.",
      source: "BRO Bodemkaart via Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/Bodemkaart_Datalabgo_gemeenten/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/Bodemkaart_Datalabgo_gemeenten/FeatureServer/0",
      category: "bodem-ondergrond",
      color: [150, 110, 70, 150],
      icon: "Layers",
      bog: true,
      isNew: true,
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) =>
        fetchDlgoWhere(
          "Bodemkaart_Datalabgo_gemeenten",
          0,
          "statnaam LIKE '%Lochem%'",
          2000,
          full
        ),
    },
    {
      id: "lch-grondwatertrappen",
      name: "Grondwatertrappenkaart",
      description: "Grondwatertrappen (GT) in Lochem — de gemiddeld hoogste en laagste grondwaterstanden per vlak, per gemeente ontsloten door Datalab Gelderland Oost. Relevant voor ontwatering, funderingen en klimaatadaptatie.",
      source: "BRO Grondwatertrappen via Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/Grondwatertrappen_Datalabgo_gemeenten/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/Grondwatertrappen_Datalabgo_gemeenten/FeatureServer/0",
      category: "bodem-ondergrond",
      color: [70, 130, 180, 150],
      icon: "Droplets",
      bog: true,
      isNew: true,
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 5000,
      fetchData: (full) =>
        fetchDlgoWhere(
          "Grondwatertrappen_Datalabgo_gemeenten",
          0,
          "statnaam LIKE '%Lochem%'",
          5000,
          full
        ),
    },
    {
      id: "lch-krw-oppervlaktewateren",
      name: "KRW-oppervlaktewateren (DLGO9)",
      description: "Kaderrichtlijn Water-oppervlaktewaterlichamen in oost-Gelderland (DLGO9-regio inclusief Lochem), met KRW-type en waternaam — relevant voor grondwater-oppervlaktewaterinteractie en waterkwaliteit.",
      source: "Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/KRWoppervlaktewateren_DLGO9_short/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/KRWoppervlaktewateren_DLGO9_short/FeatureServer/0",
      category: "bodem-ondergrond",
      color: [40, 110, 170, 160],
      icon: "Waves",
      bog: true,
      isNew: true,
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("KRWoppervlaktewateren_DLGO9_short", 0, 2000, full),
    },

    // ═══════════════════════════════════════
    // GROEN & ECOLOGIE
    // ═══════════════════════════════════════
    {
      id: "lch-basiskwaliteit-landschap",
      name: "Basiskwaliteit landschap & biodiversiteit",
      description: "Lochem-specifieke kaart van basiskwaliteit landschap en biodiversiteit per landschapstype, gepubliceerd door Datalab Gelderland Oost.",
      source: "Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/Basiskwaliteit_landschap_en_biodiversiteit_Lochem/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/Basiskwaliteit_landschap_en_biodiversiteit_Lochem/FeatureServer/0",
      category: "groen-ecologie",
      color: [40, 160, 80, 160],
      icon: "Leaf",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("Basiskwaliteit_landschap_en_biodiversiteit_Lochem", 0, 2000, full),
    },
    {
      id: "lch-bomen-referentie",
      name: "Bomen — referentie 2026",
      description: "Referentiebestand voor de gemeentelijke bomen in Lochem, beheer door CirculusBeheer (publieke ruimte).",
      source: "CirculusBeheer",
      sourceUrl: `${CIRC}/Lochem_Bomen_2026_referentie/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/7Hne9Ajbj36KaHMj/…/Lochem_Bomen_2026_referentie/FeatureServer/5",
      category: "groen-ecologie",
      color: [20, 130, 40, 220],
      icon: "TreePine",
      visible: false,
      loading: false,
      pointType: "circle",
      radius: 3,
      defaultLimit: 2000,
      // Upstream herindexeerde de service: de bomenlaag staat op layer-id 5 (id 0 bestaat niet meer).
      fetchData: (full) => fetchCirc("Lochem_Bomen_2026_referentie", 5, 2000, full),
    },
    {
      id: "lch-bomen-snoeiplanning",
      name: "Bomen — snoeiplanning publiek",
      description: "Publieke snoeiplanning voor bomen in Lochem (welke bomen wanneer worden gesnoeid).",
      source: "CirculusBeheer",
      sourceUrl: `${CIRC}/Lochem_Bomen_2025_snoeiplanning_publiek/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/7Hne9Ajbj36KaHMj/…/Lochem_Bomen_2025_snoeiplanning_publiek/FeatureServer/5",
      category: "groen-ecologie",
      color: [180, 120, 30, 200],
      icon: "TreePine",
      visible: false,
      loading: false,
      pointType: "circle",
      radius: 3,
      defaultLimit: 2000,
      // Upstream herindexeerde de service: de bomenlaag staat op layer-id 5 (id 0 bestaat niet meer).
      fetchData: (full) => fetchCirc("Lochem_Bomen_2025_snoeiplanning_publiek", 5, 2000, full),
    },
    {
      id: "lch-groen-per-buurt",
      name: "Groen per buurt (DLGO9)",
      description: "Percentage groen per buurt in oost-Gelderland (DLGO9-regio inclusief Lochem). Berekend uit Top10NL en BGT begroeid terreindeel.",
      source: "Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/Groen_per_buurt/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/Groen_per_buurt/FeatureServer/1",
      category: "groen-ecologie",
      color: [70, 180, 100, 140],
      icon: "Leaf",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("Groen_per_buurt", 1, 2000, full),
    },
    {
      id: "lch-groene-ontwikkelingszones",
      name: "Groene Ontwikkelingszones (DLGO9)",
      description: "Door de provincie Gelderland aangewezen Groene Ontwikkelingszones — corridors voor natuurnetwerk-uitbreiding.",
      source: "Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/Groene_ontwikkelingszones_DLGO9/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/Groene_ontwikkelingszones_DLGO9/FeatureServer/0",
      category: "groen-ecologie",
      color: [30, 150, 70, 130],
      icon: "Leaf",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("Groene_ontwikkelingszones_DLGO9", 0, 2000, full),
    },
    {
      id: "lch-nationaal-landschap",
      name: "Nationaal Landschap (DLGO9)",
      description: "Het deel van de aangewezen Nationale Landschappen in oost-Gelderland dat buiten GNN en GO valt — beleidsmatig relevant voor RO.",
      source: "Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/Nationaal_landschap_buiten_GNN_en_GO_DLGO9/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/Nationaal_landschap_buiten_GNN_en_GO_DLGO9/FeatureServer/0",
      category: "groen-ecologie",
      color: [80, 140, 60, 110],
      icon: "Mountain",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("Nationaal_landschap_buiten_GNN_en_GO_DLGO9", 0, 2000, full),
    },
    {
      id: "lch-speel-sport-locaties",
      name: "Speel- en sportlocaties (hittestress)",
      description: "Speel- en sportlocaties in Lochem met hun gemeten hittestressniveau (gridcode/Stressniveau).",
      source: "Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/Lochem_speel_sport_locaties_gT_stressniv/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/Lochem_speel_sport_locaties_gT_stressniv/FeatureServer/0",
      category: "groen-ecologie",
      color: [220, 140, 50, 220],
      icon: "Dumbbell",
      visible: false,
      loading: false,
      pointType: "circle",
      radius: 5,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("Lochem_speel_sport_locaties_gT_stressniv", 0, 2000, full),
    },

    // ═══════════════════════════════════════
    // OMGEVINGSFACTOREN
    // ═══════════════════════════════════════
    {
      id: "lch-grijs-per-buurt",
      name: "Grijs per buurt 2020",
      description: "Percentage verharding (grijs) per buurt in oost-Gelderland — complementair aan Groen per buurt.",
      source: "Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/Grijs_per_buurt_2020/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/Grijs_per_buurt_2020/FeatureServer/0",
      category: "omgevingsfactoren",
      color: [120, 120, 130, 140],
      icon: "Building2",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("Grijs_per_buurt_2020", 0, 2000, full),
    },
    {
      id: "lch-schaduw-fiets-wandel",
      name: "Schaduw fiets/wandelwegen (DLGO9)",
      description: "Totaalpercentage schaduw langs fiets- en wandelwegen — relevant voor klimaatadaptief mobiliteitsbeleid.",
      source: "Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/totaalpercentage_schaduw_fiets_wandelwegen_DLGO9/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/totaalpercentage_schaduw_fiets_wandelwegen_DLGO9/FeatureServer/54",
      category: "omgevingsfactoren",
      color: [60, 100, 80, 160],
      icon: "Snowflake",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("totaalpercentage_schaduw_fiets_wandelwegen_DLGO9", 54, 2000, full),
    },

    // ═══════════════════════════════════════
    // GEBOUWEN & INFRA
    // ═══════════════════════════════════════
    {
      id: "lch-plannen-woningen",
      name: "Plannen woningen (≥25 wooneenheden)",
      description: "Openbaar bekende woningbouwplannen in Lochem vanaf 25 wooneenheden.",
      source: "Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/Plannen_woningen_vanaf25_openbaarbekend_short/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/Plannen_woningen_vanaf25_openbaarbekend_short/FeatureServer/0",
      category: "gebouwen-infra",
      color: [200, 80, 60, 200],
      icon: "Home",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("Plannen_woningen_vanaf25_openbaarbekend_short", 0, 2000, full),
    },
    {
      id: "lch-wrij-transportleidingriool",
      name: "WRIJ Transportleidingriool",
      description: "Transportleidingen van Waterschap Rijn en IJssel in oost-Gelderland — bovengemeentelijk rioolnetwerk.",
      source: "Waterschap Rijn en IJssel via Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/WRIJ_transportleidingriool_OG/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/WRIJ_transportleidingriool_OG/FeatureServer/0",
      category: "gebouwen-infra",
      color: [80, 120, 200, 200],
      icon: "Pipette",
      visible: false,
      loading: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("WRIJ_transportleidingriool_OG", 0, 2000, full),
    },

    // ═══════════════════════════════════════
    // VERKEER & LOGISTIEK
    // ═══════════════════════════════════════
    {
      id: "lch-plannen-verkeer",
      name: "Verkeerplannen maart 2025",
      description: "Aangekondigde verkeers- en infrastructuurprojecten in Lochem — peildatum maart 2025.",
      source: "Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/Lochem_plannen_verkeer_maart25/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/Lochem_plannen_verkeer_maart25/FeatureServer/0",
      category: "verkeer-logistiek",
      color: [240, 160, 60, 220],
      icon: "Construction",
      visible: false,
      loading: false,
      pointType: "circle",
      radius: 5,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("Lochem_plannen_verkeer_maart25", 0, 2000, full),
    },

    // ═══════════════════════════════════════
    // VEILIGHEID
    // ═══════════════════════════════════════
    {
      id: "lch-zuiderenk-wateroverlast-begaanbaarheid",
      name: "Zuiderenk wateroverlast — begaanbaarheid",
      description: "Begaanbaarheidsanalyse bij wateroverlast in de wijk Zuiderenk (Lochem) — straten geclassificeerd op doorgang bij heftige neerslag.",
      source: "Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/Zuiderenk_wateroverlastbegaanbaarheid/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/Zuiderenk_wateroverlastbegaanbaarheid/FeatureServer/0",
      category: "veiligheid",
      color: [60, 120, 220, 200],
      icon: "Waves",
      visible: false,
      loading: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("Zuiderenk_wateroverlastbegaanbaarheid", 0, 2000, full),
    },
    {
      id: "lch-zuiderenk-wateroverlast-panden",
      name: "Zuiderenk wateroverlast — risicopanden",
      description: "Panden in de wijk Zuiderenk (Lochem) met verhoogd risico op wateroverlast bij hevige neerslag.",
      source: "Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/Zuiderenk_wateroverlast_panden_kort/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/Zuiderenk_wateroverlast_panden_kort/FeatureServer/0",
      category: "veiligheid",
      color: [200, 80, 80, 220],
      icon: "AlertTriangle",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("Zuiderenk_wateroverlast_panden_kort", 0, 2000, full),
    },
    {
      id: "lch-kwetsbare-funderingen",
      name: "Kwetsbare stedelijke gebieden — funderingen (DLGO9)",
      description: "Gebieden in oost-Gelderland met verhoogd risico op funderingsschade door grondwaterstand-verandering.",
      source: "Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/kwetsbare_stedelijke_gebieden_funderingen_DLGO9/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/kwetsbare_stedelijke_gebieden_funderingen_DLGO9/FeatureServer/8",
      category: "veiligheid",
      color: [180, 100, 50, 200],
      icon: "AlertTriangle",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("kwetsbare_stedelijke_gebieden_funderingen_DLGO9", 8, 2000, full),
    },

    // ═══════════════════════════════════════
    // SOCIAAL-ECONOMISCH
    // ═══════════════════════════════════════
    {
      id: "lch-kwetsbare-inwoners",
      name: "Gebouwen met zeer kwetsbare inwoners (DLGO9)",
      description: "Gebouwen met de meest kwetsbare gebruiksfuncties (zorginstellingen, kinderopvang, scholen) — peildatum dec 2025.",
      source: "Datalab Gelderland Oost",
      sourceUrl: `${DLGO}/gebouwen_met_zeer_kwetsbare_inwoners_DLGO9_2025dec/FeatureServer`,
      endpoint: "services-eu1.arcgis.com/VV2g0JnRRF5xL5uh/…/gebouwen_met_zeer_kwetsbare_inwoners_DLGO9_2025dec/FeatureServer/0",
      category: "sociaal-economisch",
      color: [180, 60, 140, 220],
      icon: "Accessibility",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      defaultLimit: 2000,
      fetchData: (full) => fetchDlgo("gebouwen_met_zeer_kwetsbare_inwoners_DLGO9_2025dec", 0, 2000, full),
    },
  ];
}
