/**
 * Rotterdam — municipal layers discovered 2026-05-08.
 *
 * Source: services.arcgis.com/zP1tGdLpGvt2qNJ6 (Gemeente Rotterdam GIS)
 *         services.arcgis.com/nSZVuSZjHpEZZbRo (Esri NL / Rotterdam)
 *         data.rotterdam.nl (Rotterdam Open Data portal)
 * Auto-generated by /promote-city; review before commit.
 */

import type { CityConfig } from "../../cities";
import type { DataSource } from "../types";
import { fetchGeoJSON } from "../fetchers";

const RTD_GIS = "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services";
const RTD_NL  = "https://services.arcgis.com/nSZVuSZjHpEZZbRo/arcgis/rest/services";
const RTD_OD  = "https://data.rotterdam.nl/api/explore/v2.1/catalog/datasets";

function fetchRtd(
  service: string,
  layerId: number,
  maxFeatures = 2000,
  full?: boolean
): Promise<GeoJSON.FeatureCollection> {
  const count = full ? 50000 : maxFeatures;
  const url = `${RTD_GIS}/${service}/FeatureServer/${layerId}/query?where=1%3D1&outFields=*&outSR=4326&f=geojson&resultRecordCount=${count}`;
  return fetchGeoJSON(url);
}

function fetchRtdNl(
  service: string,
  layerId: number,
  maxFeatures = 2000,
  full?: boolean
): Promise<GeoJSON.FeatureCollection> {
  const count = full ? 50000 : maxFeatures;
  const url = `${RTD_NL}/${service}/FeatureServer/${layerId}/query?where=1%3D1&outFields=*&outSR=4326&f=geojson&resultRecordCount=${count}`;
  return fetchGeoJSON(url);
}

function fetchRtdOD(
  datasetId: string,
  limit = 2000,
  full?: boolean
): Promise<GeoJSON.FeatureCollection> {
  const count = full ? 50000 : limit;
  const url = `${RTD_OD}/${datasetId}/exports/geojson?limit=${count}`;
  return fetchGeoJSON(url);
}

export function buildRotterdamLayers(_city: CityConfig): DataSource[] {
  const layers: DataSource[] = [
    // ═══════════════════════════════════════
    // MOBILITEITSDIENSTEN
    // ═══════════════════════════════════════
    {
      id: "rtd-laadpalen",
      name: "Laadpalen Rotterdam",
      description: "Gemeentelijke oplaadpalen voor elektrische voertuigen in Rotterdam (beheer Gemeente Rotterdam).",
      source: "Gemeente Rotterdam GIS",
      sourceUrl: "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services/Laadpalen/FeatureServer",
      endpoint: "services.arcgis.com/zP1tGdLpGvt2qNJ6/…/Laadpalen/FeatureServer/0",
      category: "mobiliteitsdiensten",
      color: [0, 200, 100, 220],
      icon: "Zap",
      visible: false,
      loading: false,
      pointType: "circle",
      radius: 5,
      defaultLimit: 2000,
      fetchData: (full) => fetchRtd("Laadpalen", 0, 2000, full),
    },
    {
      id: "rtd-metro-stops",
      name: "Metrostations Rotterdam",
      description: "Haltegebieden van de RET metro in Rotterdam (geometrie als vlak per halte).",
      source: "Gemeente Rotterdam GIS",
      sourceUrl: "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services/Metro_Tram_Bus_stops/FeatureServer",
      endpoint: "services.arcgis.com/zP1tGdLpGvt2qNJ6/…/Metro_Tram_Bus_stops/FeatureServer/0",
      category: "mobiliteitsdiensten",
      color: [0, 80, 180, 200],
      icon: "Train",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 500,
      fetchData: (full) => fetchRtd("Metro_Tram_Bus_stops", 0, 500, full),
    },
    {
      id: "rtd-tram-stops",
      name: "Tramhaltes Rotterdam",
      description: "Haltegebieden van RET-tramlijnen in Rotterdam.",
      source: "Gemeente Rotterdam GIS",
      sourceUrl: "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services/Metro_Tram_Bus_stops/FeatureServer",
      endpoint: "services.arcgis.com/zP1tGdLpGvt2qNJ6/…/Metro_Tram_Bus_stops/FeatureServer/2",
      category: "mobiliteitsdiensten",
      color: [255, 120, 0, 200],
      icon: "Tram",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 500,
      fetchData: (full) => fetchRtd("Metro_Tram_Bus_stops", 2, 500, full),
    },
    {
      id: "rtd-metrolijnen",
      name: "Metrolijnen RET",
      description: "Tracé van de RET-metrolijnen A t/m E door Rotterdam en de agglomeratie (peiljaar 2022).",
      source: "Gemeente Rotterdam GIS",
      sourceUrl: "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services/Metrolijnen/FeatureServer",
      endpoint: "services.arcgis.com/zP1tGdLpGvt2qNJ6/…/Metrolijnen/FeatureServer/1",
      category: "mobiliteitsdiensten",
      color: [0, 60, 160, 220],
      icon: "Train",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 3,
      defaultLimit: 200,
      fetchData: (full) => fetchRtd("Metrolijnen", 1, 200, full),
    },
    {
      id: "rtd-publieke-laadpalen",
      name: "Publieke Laadpalen Rotterdam (Esri NL)",
      description: "Publieke laadpaallocaties in de gemeente Rotterdam — opgehaald uit de Esri NL database (EQUANS e.a.).",
      source: "Esri NL / Gemeente Rotterdam",
      sourceUrl: "https://services.arcgis.com/nSZVuSZjHpEZZbRo/arcgis/rest/services/Publieke_Laadpalen_Rotterdam/FeatureServer",
      endpoint: "services.arcgis.com/nSZVuSZjHpEZZbRo/…/Publieke_Laadpalen_Rotterdam/FeatureServer/12",
      category: "mobiliteitsdiensten",
      color: [0, 180, 80, 200],
      icon: "Zap",
      visible: false,
      loading: false,
      pointType: "circle",
      radius: 4,
      defaultLimit: 2000,
      fetchData: (full) => fetchRtdNl("Publieke_Laadpalen_Rotterdam", 12, 2000, full),
    },

    // ═══════════════════════════════════════
    // VERKEER & LOGISTIEK
    // ═══════════════════════════════════════
    {
      id: "rtd-fietspaden",
      name: "Fietspaden Rotterdam",
      description: "BGT-gebaseerde fietspadvlakken in Rotterdam met breedtemeting en verhardingstype.",
      source: "Gemeente Rotterdam GIS",
      sourceUrl: "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services/Fietspaden/FeatureServer",
      endpoint: "services.arcgis.com/zP1tGdLpGvt2qNJ6/…/Fietspaden/FeatureServer/0",
      category: "verkeer-logistiek",
      color: [50, 200, 80, 180],
      icon: "Bike",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 3000,
      fetchData: (full) => fetchRtd("Fietspaden", 0, 3000, full),
    },
    {
      id: "rtd-maxsnelheden",
      name: "Maximumsnelheden Rotterdam",
      description: "NWB-wegvakken in Rotterdam met maximumsnelheid (30 / 50 / 70 / 100 km/h) op basis van actueel wegenbestand.",
      source: "Gemeente Rotterdam GIS",
      sourceUrl: "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services/NWB_Rotterdam_WegenMaxSnelheden/FeatureServer",
      endpoint: "services.arcgis.com/zP1tGdLpGvt2qNJ6/…/NWB_Rotterdam_WegenMaxSnelheden/FeatureServer/0",
      category: "verkeer-logistiek",
      color: [220, 50, 50, 200],
      icon: "Gauge",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 5000,
      fetchData: (full) => fetchRtd("NWB_Rotterdam_WegenMaxSnelheden", 0, 5000, full),
    },

    // ═══════════════════════════════════════
    // GROEN & ECOLOGIE
    // ═══════════════════════════════════════
    {
      id: "rtd-monumentale-bomen",
      name: "Monumentale Bomen Rotterdam",
      description: "Gemeentelijk register van monumentale bomen in Rotterdam met soort, stamdiameter en aanlegjaar.",
      source: "Gemeente Rotterdam GIS",
      sourceUrl: "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services/Monumentale_bomen_Rotterdam/FeatureServer",
      endpoint: "services.arcgis.com/zP1tGdLpGvt2qNJ6/…/Monumentale_bomen_Rotterdam/FeatureServer/0",
      category: "groen-ecologie",
      color: [34, 139, 34, 220],
      icon: "TreePine",
      visible: false,
      loading: false,
      pointType: "circle",
      radius: 5,
      defaultLimit: 2000,
      fetchData: (full) => fetchRtd("Monumentale_bomen_Rotterdam", 0, 2000, full),
    },

    // ═══════════════════════════════════════
    // OMGEVINGSFACTOREN
    // ═══════════════════════════════════════
    {
      id: "rtd-hittestress",
      name: "Hittestress Rotterdam",
      description: "Kaart met zones voor fijnstof, warme nachten en hittestress in Rotterdam op gridniveau.",
      source: "Gemeente Rotterdam GIS",
      sourceUrl: "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services/Hitte_Warme_Nachten_en_hittestress_WFL1/FeatureServer",
      endpoint: "services.arcgis.com/zP1tGdLpGvt2qNJ6/…/Hitte_Warme_Nachten_en_hittestress_WFL1/FeatureServer/2",
      category: "omgevingsfactoren",
      color: [255, 80, 0, 160],
      icon: "Thermometer",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 3000,
      fetchData: (full) => fetchRtd("Hitte_Warme_Nachten_en_hittestress_WFL1", 2, 3000, full),
    },
    {
      id: "rtd-koele-plekken",
      name: "Koele Verblijfsplekken Rotterdam",
      description: "Bestaande koele verblijfslocaties buiten (parken, pleinen, waterpartijen) als hittebestendige ontmoetingsplekken.",
      source: "Gemeente Rotterdam GIS",
      sourceUrl: "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services/Bestaande_koele_plekken_buiten/FeatureServer",
      endpoint: "services.arcgis.com/zP1tGdLpGvt2qNJ6/…/Bestaande_koele_plekken_buiten/FeatureServer/0",
      category: "omgevingsfactoren",
      color: [0, 180, 220, 180],
      icon: "Snowflake",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 500,
      fetchData: (full) => fetchRtd("Bestaande_koele_plekken_buiten", 0, 500, full),
    },

    // ═══════════════════════════════════════
    // BODEM & ONDERGROND
    // ═══════════════════════════════════════
    {
      id: "rtd-grondwaterstanden",
      name: "Grondwaterstanden Rotterdam",
      description: "Meetpunten voor zomer- en wintergrondwaterstand in Rotterdam met historische statistieken (min/max/percentiel).",
      source: "Gemeente Rotterdam GIS",
      sourceUrl: "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services/Grondwaterstanden_zomerwinter_Rotterdam/FeatureServer",
      endpoint: "services.arcgis.com/zP1tGdLpGvt2qNJ6/…/Grondwaterstanden_zomerwinter_Rotterdam/FeatureServer/0",
      category: "bodem-ondergrond",
      color: [0, 100, 200, 200],
      icon: "Droplets",
      visible: false,
      loading: false,
      pointType: "circle",
      radius: 5,
      defaultLimit: 500,
      fetchData: (full) => fetchRtd("Grondwaterstanden_zomerwinter_Rotterdam", 0, 500, full),
    },
    {
      id: "rtd-bodemdaling",
      name: "Bodemdaling Rotterdam",
      description: "Achtergrondzetting (bodemdaling) per subbuurt, buurt en gebied in Rotterdam — 25e percentiel in mm/jaar.",
      source: "Gemeente Rotterdam GIS",
      sourceUrl: "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services/Bodemdaling_Achtergrondzetting/FeatureServer",
      endpoint: "services.arcgis.com/zP1tGdLpGvt2qNJ6/…/Bodemdaling_Achtergrondzetting/FeatureServer/0",
      category: "bodem-ondergrond",
      color: [140, 90, 40, 180],
      icon: "Layers",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      colorMode: "auto-bucket",
      defaultLimit: 1000,
      fetchData: (full) => fetchRtd("Bodemdaling_Achtergrondzetting", 0, 1000, full),
    },

    // ═══════════════════════════════════════
    // GEBOUWEN & INFRA
    // ═══════════════════════════════════════
    {
      id: "rtd-funderingstypekaart",
      name: "Funderingstypekaart Rotterdam",
      description: "Publieke versie van de funderingstypekaart per pand in Rotterdam (betonpalen, niet-onderkelderd, onbekend).",
      source: "Gemeente Rotterdam GIS",
      sourceUrl: "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services/Funderingstypekaart_V5_publiek/FeatureServer",
      endpoint: "services.arcgis.com/zP1tGdLpGvt2qNJ6/…/Funderingstypekaart_V5_publiek/FeatureServer/2",
      category: "gebouwen-infra",
      color: [180, 120, 60, 180],
      icon: "Building2",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 3000,
      fetchData: (full) => fetchRtd("Funderingstypekaart_V5_publiek", 2, 3000, full),
    },

    // ═══════════════════════════════════════
    // GEZONDHEID
    // ═══════════════════════════════════════
    {
      id: "rtd-watertappunten",
      name: "Watertappunten Rotterdam",
      description: "Openbare drinkwatertappunten (Evides / Join the Pipe) in de openbare ruimte van Rotterdam.",
      source: "Gemeente Rotterdam GIS",
      sourceUrl: "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services/WaterTappunt_gemeente_Rotterdam/FeatureServer",
      endpoint: "services.arcgis.com/zP1tGdLpGvt2qNJ6/…/WaterTappunt_gemeente_Rotterdam/FeatureServer/0",
      category: "gezondheid-norm",
      color: [0, 160, 220, 220],
      icon: "Droplets",
      visible: false,
      loading: false,
      pointType: "circle",
      radius: 6,
      defaultLimit: 200,
      fetchData: (full) => fetchRtd("WaterTappunt_gemeente_Rotterdam", 0, 200, full),
    },

    // ═══════════════════════════════════════
    // ENERGIE
    // ═══════════════════════════════════════
    {
      id: "rtd-gasvervanging",
      name: "Gasvervanging Rotterdam (Stedin)",
      description: "Gastransportleidingen in Rotterdam die worden vervangen door Stedin, gecategoriseerd naar leeftijd (jonger/ouder dan 30 jaar).",
      source: "Gemeente Rotterdam GIS",
      sourceUrl: "https://services.arcgis.com/zP1tGdLpGvt2qNJ6/arcgis/rest/services/GasvervangingRotterdam/FeatureServer",
      endpoint: "services.arcgis.com/zP1tGdLpGvt2qNJ6/…/GasvervangingRotterdam/FeatureServer/0",
      category: "energie",
      color: [255, 200, 0, 200],
      icon: "Flame",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 3000,
      fetchData: (full) => fetchRtd("GasvervangingRotterdam", 0, 3000, full),
    },

    // ═══════════════════════════════════════
    // ROTTERDAM OPEN DATA PORTAL (geo)
    // ═══════════════════════════════════════
    {
      id: "rtd-grondgebruik",
      name: "Functioneel Grondgebruik Rotterdam",
      description: "Percentage groen, bebouwing, water en infrastructuur per buurt op maaiveldniveau (peiljaar 2017, 920 buurten).",
      source: "Rotterdam Open Data",
      sourceUrl: "https://data.rotterdam.nl/explore/dataset/functioneel-stedelijk-grondgebruik-op-maaiveldniveau",
      endpoint: "data.rotterdam.nl/api/explore/v2.1/catalog/datasets/functioneel-stedelijk-grondgebruik-op-maaiveldniveau/exports/geojson",
      category: "gebouwen-infra",
      color: [100, 160, 80, 160],
      icon: "Map",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      colorMode: "auto-bucket",
      defaultLimit: 1000,
      fetchData: (full) => fetchRtdOD("functioneel-stedelijk-grondgebruik-op-maaiveldniveau", 1000, full),
      freshness: { frequency: "ad-hoc", reference: "2017" },
    },
  ];

  return layers.sort((a, b) => a.id.localeCompare(b.id));
}
