/**
 * Zwolle-specific layers (~100): everything backed by gisservices.zwolle.nl
 * plus Geoportaal Overijssel B22/B23/B42 services. Only emitted when the
 * active CityConfig is Zwolle.
 */

import type { CityConfig } from "../../cities";
import type { DataSource } from "../types";
import {
  fetchArcGISQuery,
  fetchEmpty,
  fetchGeoJSON,
} from "../fetchers";

export function buildZwolleLayers(city: CityConfig): DataSource[] {
  const ZWOLLE_GIS = city.municipalGIS!.baseUrl; // guaranteed for Zwolle
  const bboxWFS = city.bboxWFS;
  const fzg = (
    service: string,
    layerId: number,
    serverType: "FeatureServer" | "MapServer" = "FeatureServer",
    maxFeatures = 2000,
    full = false
  ) =>
    fetchArcGISQuery(ZWOLLE_GIS, service, layerId, serverType, maxFeatures, full);

  return [
    // ═══════════════════════════════════════
    // VERKEER & TRANSPORT
    // ═══════════════════════════════════════
    {
      id: "wegwerkzaamheden",
      name: "Wegwerkzaamheden",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Wegwerkzaamheden/FeatureServer/0",
      source: "Gemeente Zwolle GIS (NDW)",
      description: "Actuele wegwerkzaamheden en omleidingen (NDW data)",
      category: "verkeer-logistiek",
      color: [255, 120, 0, 200],
      icon: "Construction",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 3,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Wegwerkzaamheden", 0, "FeatureServer", 2000, full),
    },
    {
      id: "wegwerkzaamheden-omleiding",
      name: "Omleidingen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Wegwerkzaamheden/FeatureServer/1",
      source: "Gemeente Zwolle GIS (NDW)",
      description: "Omleidingsroutes bij wegwerkzaamheden",
      category: "verkeer-logistiek",
      color: [255, 200, 0, 180],
      icon: "ArrowRightLeft",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Wegwerkzaamheden", 1, "FeatureServer", 2000, full),
    },
    {
      id: "hoofdfietsroutes",
      name: "Hoofdfietsroutes",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Hoofdfietsroutes/FeatureServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Regionale fietsverbindingen en stedelijke verbindingsroutes",
      category: "verkeer-logistiek",
      color: [50, 200, 255, 200],
      icon: "Bike",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Hoofdfietsroutes", 0, "FeatureServer", 2000, full),
    },
    {
      id: "strooiroute-fiets",
      name: "Strooiroute Fietspaden",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Strooiroute/FeatureServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Strooiroutes voor fietspaden in de winter",
      category: "verkeer-logistiek",
      color: [180, 220, 255, 180],
      icon: "Snowflake",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Strooiroute", 0, "FeatureServer", 2000, full),
    },
    {
      id: "strooiroute-weg",
      name: "Strooiroute Wegen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Strooiroute/FeatureServer/1",
      source: "Gemeente Zwolle GIS",
      description: "Strooiroutes voor wegen in de winter",
      category: "verkeer-logistiek",
      color: [140, 180, 255, 180],
      icon: "Snowflake",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Strooiroute", 1, "FeatureServer", 2000, full),
    },
    {
      id: "parkeerautomaten",
      name: "Parkeerautomaten",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Parkeren/FeatureServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Locaties van parkeerautomaten",
      category: "verkeer-logistiek",
      color: [0, 120, 255, 200],
      icon: "ParkingCircle",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 5,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Parkeren", 0, "FeatureServer", 2000, full),
    },
    {
      id: "parkeer-invaliden",
      name: "Gehandicaptenparkeerplaatsen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Parkeren/FeatureServer/3",
      source: "Gemeente Zwolle GIS",
      description: "Gehandicaptenparkeerplaatsen in Zwolle",
      category: "verkeer-logistiek",
      color: [0, 80, 220, 200],
      icon: "Accessibility",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 5,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Parkeren", 3, "FeatureServer", 2000, full),
    },
    {
      id: "parkeer-zones",
      name: "Parkeerzones",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Parkeren/FeatureServer/7",
      source: "Gemeente Zwolle GIS",
      description: "Parkeer reguleringsgebieden",
      category: "verkeer-logistiek",
      color: [0, 100, 200, 100],
      icon: "ParkingCircle",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Parkeren", 7, "FeatureServer", 2000, full),
    },
    {
      id: "parkeer-betaald",
      name: "Betaald Parkeren",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Parkeren/FeatureServer/4",
      source: "Gemeente Zwolle GIS",
      description: "Zones met betaald parkeren",
      category: "verkeer-logistiek",
      color: [60, 60, 200, 100],
      icon: "CreditCard",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Parkeren", 4, "FeatureServer", 2000, full),
    },
    {
      id: "parkeervakken",
      name: "Parkeervakken",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Parkeervakken/FeatureServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Individuele parkeervakken op straat",
      category: "verkeer-logistiek",
      color: [100, 140, 255, 140],
      icon: "ParkingCircle",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Parkeervakken", 0, "FeatureServer", 2000, full),
    },
    {
      id: "laadpalen",
      name: "Laadpalen (bestaand)",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Laadpalen/FeatureServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Bestaande laadpaallocaties voor elektrische auto's",
      category: "mobiliteitsdiensten",
      color: [0, 220, 120, 200],
      icon: "Zap",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 5,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Laadpalen", 0, "FeatureServer", 2000, full),
    },
    {
      id: "laadpalen-aangevraagd",
      name: "Laadpalen (aangevraagd)",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Laadpalen/FeatureServer/1",
      source: "Gemeente Zwolle GIS",
      description: "Aangevraagde laadpaallocaties",
      category: "mobiliteitsdiensten",
      color: [0, 180, 100, 150],
      icon: "Zap",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 5,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Laadpalen", 1, "FeatureServer", 2000, full),
    },

    // ═══════════════════════════════════════
    // GEBOUWEN & ADRESSEN
    // ═══════════════════════════════════════
    {
      id: "bag-zwolle",
      name: "BAG Zwolle (lokaal)",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/BAG/FeatureServer/6",
      source: "Gemeente Zwolle GIS",
      description: "BAG panden via Zwolle GIS server",
      category: "gebouwen-infra",
      color: [160, 80, 180, 120],
      icon: "Building2",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 1000,
      fetchData: async (full) => fzg("BAG", 6, "FeatureServer", 1000, full),
    },
    {
      id: "energielabels",
      name: "Energielabels",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Energielabels/FeatureServer/0",
      source: "Gemeente Zwolle GIS (EP-online RVO)",
      description: "Energielabels van gebouwen in Zwolle (bron: EP-online RVO)",
      category: "energie",
      color: [255, 200, 50, 180],
      icon: "Gauge",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 3,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Energielabels", 0, "FeatureServer", 2000, full),
      colorMap: {
        property: "ENERGIELABEL",
        values: {
          "A++++": [28, 82, 2, 180],
          "A+++": [28, 82, 2, 180],
          "A++": [28, 82, 2, 180],
          "A+": [28, 82, 2, 180],
          "A": [38, 115, 0, 180],
          "B": [111, 166, 0, 180],
          "C": [230, 230, 0, 180],
          "D": [230, 149, 0, 180],
          "E": [255, 170, 0, 180],
          "F": [255, 85, 0, 180],
          "G": [255, 0, 0, 180],
        },
        default: [255, 200, 50, 180],
      },
    },
    {
      id: "erfgoed-rijksmonumenten",
      name: "Rijksmonumenten",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Erfgoed/MapServer/4",
      source: "Gemeente Zwolle GIS",
      description: "Door het Rijk aangewezen monumenten",
      category: "gebouwen-infra",
      color: [200, 150, 50, 180],
      icon: "Landmark",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Erfgoed", 4, "MapServer", 2000, full),
    },
    {
      id: "erfgoed-gemeentemonumenten",
      name: "Gemeentelijke Monumenten",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Erfgoed/MapServer/5",
      source: "Gemeente Zwolle GIS",
      description: "Door de gemeente aangewezen monumenten",
      category: "gebouwen-infra",
      color: [180, 130, 40, 160],
      icon: "Landmark",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Erfgoed", 5, "MapServer", 2000, full),
    },
    {
      id: "beschermd-stadsgezicht",
      name: "Beschermd Stadsgezicht",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Erfgoed/MapServer/6",
      source: "Gemeente Zwolle GIS",
      description: "Beschermd stadsgezicht gebied",
      category: "gebouwen-infra",
      color: [220, 180, 100, 100],
      icon: "Castle",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Erfgoed", 6, "MapServer", 2000, full),
    },

    // ═══════════════════════════════════════
    // OPENBARE RUIMTE
    // ═══════════════════════════════════════
    {
      id: "bomen",
      name: "Bomen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/BOR_groen_wegen/FeatureServer/2",
      source: "Gemeente Zwolle GIS",
      description: "Alle gemeentelijke bomen met soort, hoogte en diameter",
      category: "groen-ecologie",
      color: [50, 180, 80, 200],
      icon: "TreePine",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 3,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("BOR_groen_wegen", 2, "FeatureServer", 2000, full),
    },
    {
      id: "hagen",
      name: "Hagen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/BOR_groen_wegen/FeatureServer/10",
      source: "Gemeente Zwolle GIS",
      description: "Hagen in de openbare ruimte",
      category: "groen-ecologie",
      color: [30, 130, 60, 160],
      icon: "TreePine",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("BOR_groen_wegen", 10, "FeatureServer", 2000, full),
    },
    {
      id: "beplantingen",
      name: "Beplantingen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/BOR_groen_wegen/FeatureServer/12",
      source: "Gemeente Zwolle GIS",
      description: "Beplantingen en struiken in de openbare ruimte",
      category: "groen-ecologie",
      color: [60, 150, 70, 140],
      icon: "Leaf",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("BOR_groen_wegen", 12, "FeatureServer", 2000, full),
    },
    {
      id: "grassen",
      name: "Grassen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/BOR_groen_wegen/FeatureServer/11",
      source: "Gemeente Zwolle GIS",
      description: "Grasvelden en gazons",
      category: "groen-ecologie",
      color: [120, 200, 80, 120],
      icon: "Leaf",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("BOR_groen_wegen", 11, "FeatureServer", 2000, full),
    },
    {
      id: "sportvelden",
      name: "Sportvelden",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/BOR_groen_wegen/FeatureServer/8",
      source: "Gemeente Zwolle GIS",
      description: "Sportvelden in de gemeente",
      category: "groen-ecologie",
      color: [80, 200, 120, 140],
      icon: "Dumbbell",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("BOR_groen_wegen", 8, "FeatureServer", 2000, full),
    },
    {
      id: "water-bor",
      name: "Water (BOR)",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/BOR_groen_wegen/FeatureServer/14",
      source: "Gemeente Zwolle GIS",
      description: "Waterpartijen in de openbare ruimte",
      category: "groen-ecologie",
      color: [50, 130, 220, 140],
      icon: "Waves",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("BOR_groen_wegen", 14, "FeatureServer", 2000, full),
    },
    {
      id: "afvalbakken",
      name: "Afvalbakken",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/BOR_groen_wegen/FeatureServer/3",
      source: "Gemeente Zwolle GIS",
      description: "Openbare afvalbakken",
      category: "gebouwen-infra",
      color: [140, 160, 110, 200],
      icon: "Trash2",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 3,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("BOR_groen_wegen", 3, "FeatureServer", 2000, full),
    },
    {
      id: "kunstwerken",
      name: "Artistieke Kunstwerken",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Artistiekekunst/FeatureServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Kunstobjecten in de openbare ruimte",
      category: "groen-ecologie",
      color: [220, 120, 255, 200],
      icon: "Palette",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 6,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Artistiekekunst", 0, "FeatureServer", 2000, full),
    },
    {
      id: "japanse-duizendknoop",
      name: "Japanse Duizendknoop",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Japanse_duizendknoop_openbaar/FeatureServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Locaties van Japanse duizendknoop (invasieve plant)",
      category: "groen-ecologie",
      color: [200, 50, 50, 200],
      icon: "Bug",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 5,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Japanse_duizendknoop_openbaar", 0, "FeatureServer", 2000, full),
    },

    // ═══════════════════════════════════════
    // GRENZEN & GEBIEDEN
    // ═══════════════════════════════════════
    {
      id: "gemeentegrens",
      name: "Gemeentegrens",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Grenzen/FeatureServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Gemeentegrens van Zwolle",
      category: "gebouwen-infra",
      color: [255, 255, 255, 200],
      icon: "MapPin",
      visible: true,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 3,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Grenzen", 0, "FeatureServer", 2000, full),
    },
    {
      id: "stadsdelen",
      name: "Stadsdelen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Grenzen/FeatureServer/1",
      source: "Gemeente Zwolle GIS",
      description: "Stadsdelen van Zwolle",
      category: "gebouwen-infra",
      color: [255, 200, 100, 100],
      icon: "Map",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Grenzen", 1, "FeatureServer", 2000, full),
    },
    {
      id: "wijken",
      name: "Wijken",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Grenzen/FeatureServer/2",
      source: "Gemeente Zwolle GIS",
      description: "Wijkgrenzen van Zwolle",
      category: "gebouwen-infra",
      color: [255, 180, 0, 100],
      icon: "Map",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Grenzen", 2, "FeatureServer", 2000, full),
    },
    {
      id: "buurten",
      name: "Buurten",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Grenzen/FeatureServer/3",
      source: "Gemeente Zwolle GIS",
      description: "Buurtgrenzen van Zwolle",
      category: "gebouwen-infra",
      color: [200, 160, 0, 80],
      icon: "LayoutGrid",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Grenzen", 3, "FeatureServer", 2000, full),
    },
    {
      id: "bebouwde-kom-bos",
      name: "Bebouwde Kom (Boswet)",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Grenzen/FeatureServer/4",
      source: "Gemeente Zwolle GIS",
      description: "Grens bebouwde kom o.g.v. de Boswet",
      category: "groen-ecologie",
      color: [100, 200, 100, 80],
      icon: "TreePine",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Grenzen", 4, "FeatureServer", 2000, full),
    },
    {
      id: "bebouwde-kom-verkeer",
      name: "Bebouwde Kom (Verkeer)",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Grenzen/FeatureServer/5",
      source: "Gemeente Zwolle GIS",
      description: "Grens bebouwde kom o.g.v. de Wegenverkeerswet",
      category: "verkeer-logistiek",
      color: [200, 100, 100, 80],
      icon: "TrafficCone",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Grenzen", 5, "FeatureServer", 2000, full),
    },
    {
      id: "archeologie",
      name: "Archeologische Waarderingskaart",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Erfgoed/MapServer/8",
      source: "Gemeente Zwolle GIS",
      description: "Archeologische waarderings- en verwachtingsgebieden",
      category: "bodem-ondergrond",
      color: [180, 120, 60, 100],
      icon: "Search",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Erfgoed", 8, "MapServer", 2000, full),
    },

    // ═══════════════════════════════════════
    // MILIEU & KLIMAAT
    // ═══════════════════════════════════════
    {
      id: "klimaat-koelteplekken",
      name: "Koele Verblijfsplekken",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Klimaat/FeatureServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Aangename koele verblijfsplekken (potentieel)",
      category: "omgevingsfactoren",
      color: [80, 180, 220, 120],
      icon: "Thermometer",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Klimaat", 0, "FeatureServer", 2000, full),
    },
    {
      id: "klimaat-afstand-koelte",
      name: "Afstand tot Koelteplek",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Klimaat/FeatureServer/1",
      source: "Gemeente Zwolle GIS",
      description: "Afstand tot dichtstbijzijnde koelteplek",
      category: "omgevingsfactoren",
      color: [255, 140, 60, 100],
      icon: "Thermometer",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Klimaat", 1, "FeatureServer", 2000, full),
      colorMap: {
        property: "LOOPAFSTAND",
        values: {
          "< 100 meter": [85, 145, 0, 100],
          "100 - 200 meter": [164, 196, 0, 100],
          "200 - 300 meter": [255, 255, 0, 100],
          "300 - 400 meter": [255, 187, 0, 100],
          "400 - 500 meter": [255, 119, 0, 100],
          "> 500 meter": [255, 38, 0, 100],
        },
        default: [255, 140, 60, 100],
      },
    },
    {
      id: "milieu-bescherming",
      name: "Milieubeschermingsgebieden",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Milieu/MapServer/1",
      source: "Gemeente Zwolle GIS",
      description: "Beschermde milieugebieden",
      category: "groen-ecologie",
      color: [50, 200, 100, 100],
      icon: "ShieldCheck",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Milieu", 1, "MapServer", 2000, full),
    },

    // ═══════════════════════════════════════
    // VOORZIENINGEN
    // ═══════════════════════════════════════
    {
      id: "horeca",
      name: "Horeca",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Horeca_openbaar/FeatureServer/1",
      source: "Gemeente Zwolle GIS",
      description: "Horeca vergunningen en terrassen",
      category: "gebouwen-infra",
      color: [255, 140, 60, 200],
      icon: "UtensilsCrossed",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 5,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Horeca_openbaar", 1, "FeatureServer", 2000, full),
    },
    {
      id: "horeca-terrassen",
      name: "Terrassen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Horeca_openbaar/FeatureServer/2",
      source: "Gemeente Zwolle GIS",
      description: "Horeca terrassen (vlakken)",
      category: "gebouwen-infra",
      color: [255, 160, 80, 120],
      icon: "UtensilsCrossed",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Horeca_openbaar", 2, "FeatureServer", 2000, full),
    },
    {
      id: "wijkservicepunten",
      name: "Wijkservicepunten",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Wijkservicepunten/FeatureServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Wijkservicepunten en buurthuizen",
      category: "sociaal-economisch",
      color: [100, 180, 255, 200],
      icon: "MapPin",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 7,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Wijkservicepunten", 0, "FeatureServer", 2000, full),
    },
    {
      id: "riolering-putten",
      name: "Riolering Putten",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Riolering_openbaar/FeatureServer/8",
      source: "Gemeente Zwolle GIS",
      description: "Rioolputten in Zwolle",
      category: "bodem-ondergrond",
      color: [180, 130, 70, 200],
      icon: "CircleDot",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 3,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Riolering_openbaar", 8, "FeatureServer", 2000, full),
    },
    {
      id: "riolering-strengen",
      name: "Riolering Leidingen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Riolering_openbaar/FeatureServer/9",
      source: "Gemeente Zwolle GIS",
      description: "Rioolstrengen / leidingen",
      category: "bodem-ondergrond",
      color: [160, 110, 60, 180],
      icon: "Route",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Riolering_openbaar", 9, "FeatureServer", 2000, full),
    },
    {
      id: "eetbaar-groen",
      name: "Eetbaar Groen / Stadslandbouw",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Eetbaar_groen_Stadslandbouw/FeatureServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Locaties voor stadslandbouw en eetbaar groen",
      category: "groen-ecologie",
      color: [80, 200, 80, 180],
      icon: "Apple",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 6,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Eetbaar_groen_Stadslandbouw", 0, "FeatureServer", 2000, full),
    },
    {
      id: "carbid-locaties",
      name: "Carbidschieten Locaties",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Carbidschietlocaties/MapServer/2",
      source: "Gemeente Zwolle GIS",
      description: "Toegestane locaties voor carbidschieten",
      category: "veiligheid",
      color: [255, 50, 50, 180],
      icon: "Flame",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Carbidschietlocaties", 2, "MapServer", 2000, full),
    },
    {
      id: "standplaatsen",
      name: "Standplaatsen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Standplaatsenkaart/MapServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Markt- en standplaatsen",
      category: "gebouwen-infra",
      color: [200, 120, 255, 180],
      icon: "Store",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Standplaatsenkaart", 0, "MapServer", 2000, full),
    },
    {
      id: "wkpb",
      name: "WKPB Beperkingen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/WKPB/FeatureServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Publiekrechtelijke beperkingen op onroerende zaken",
      category: "gebouwen-infra",
      color: [200, 50, 120, 120],
      icon: "ShieldAlert",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("WKPB", 0, "FeatureServer", 2000, full),
    },

    // ═══════════════════════════════════════
    // BODEM (SOIL)
    // ═══════════════════════════════════════
    {
      id: "bodem-verontreinigingen",
      name: "Bodemverontreinigingen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Bodem/MapServer/2",
      source: "Gemeente Zwolle GIS",
      description: "Locaties met bodemverontreiniging (grond en grondwater)",
      category: "bodem-ondergrond",
      color: [180, 80, 40, 140],
      icon: "Bug",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Bodem", 2, "MapServer", 2000, full),
    },
    {
      id: "bodem-sanering",
      name: "Bodemsaneringsmaatregelen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Bodem/MapServer/1",
      source: "Gemeente Zwolle GIS",
      description: "Saneringsmaatregelen bij bodemverontreiniging",
      category: "bodem-ondergrond",
      color: [140, 100, 40, 120],
      icon: "ShieldCheck",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Bodem", 1, "MapServer", 2000, full),
    },
    {
      id: "bodem-locaties",
      name: "Bodemonderzoek Locaties",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Bodem/MapServer/3",
      source: "Gemeente Zwolle GIS",
      description: "Locaties van bodemonderzoeken",
      category: "bodem-ondergrond",
      color: [160, 120, 60, 100],
      icon: "Search",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Bodem", 3, "MapServer", 2000, full),
    },

    // ═══════════════════════════════════════
    // GROENEKAART (NOTABLE TREES)
    // ═══════════════════════════════════════
    {
      id: "bijzondere-bomen-particulier",
      name: "Bijzondere Bomen (Particulier)",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Groenekaart/MapServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Bijzondere en monumentale bomen in particulier bezit",
      category: "groen-ecologie",
      color: [30, 160, 50, 200],
      icon: "TreePine",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 5,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Groenekaart", 0, "MapServer", 2000, full),
    },
    {
      id: "bijzondere-bomen-gemeentelijk",
      name: "Bijzondere Bomen (Gemeentelijk)",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Groenekaart/MapServer/1",
      source: "Gemeente Zwolle GIS",
      description: "Bijzondere en monumentale gemeentelijke bomen",
      category: "groen-ecologie",
      color: [20, 140, 40, 200],
      icon: "TreePine",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 5,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Groenekaart", 1, "MapServer", 2000, full),
    },

    // ═══════════════════════════════════════
    // CIVIL ENGINEERING & STREET LIGHTING
    // ═══════════════════════════════════════
    {
      id: "civiele-kunstwerken",
      name: "Civiele Kunstwerken",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Kunstwerken/MapServer/2",
      source: "Gemeente Zwolle GIS",
      description: "Bruggen, tunnels, duikers, viaducten en andere civiele kunstwerken",
      category: "gebouwen-infra",
      color: [140, 140, 180, 160],
      icon: "Construction",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Kunstwerken", 2, "MapServer", 2000, full),
    },
    {
      id: "lichtmasten",
      name: "Lichtmasten",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Lichtmasten/MapServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Gemeentelijke straatverlichting met mast- en lamptype",
      category: "gebouwen-infra",
      color: [255, 230, 100, 180],
      icon: "Lightbulb",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Lichtmasten", 0, "MapServer", 2000, full),
    },

    // ═══════════════════════════════════════
    // FLOOD MODELING
    // ═══════════════════════════════════════
    {
      id: "regenbui-stroombanen",
      name: "Regenbui Stroombanen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Regenbui/MapServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Waterafstroomroutes bij zware regenbuien",
      category: "veiligheid",
      color: [40, 100, 220, 160],
      icon: "Droplets",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Regenbui", 0, "MapServer", 2000, full),
    },
    {
      id: "regenbui-t100-wegen",
      name: "Begaanbaarheid T100 Bui",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Regenbui/MapServer/4",
      source: "Gemeente Zwolle GIS",
      description: "Begaanbaarheid wegen bij T100 bui (67mm/uur)",
      category: "veiligheid",
      color: [60, 60, 200, 140],
      icon: "Droplets",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Regenbui", 4, "MapServer", 2000, full),
      colorMap: {
        property: "SYM",
        values: {
          "Begaanbaar": [23, 147, 0, 140],
          "Hoofdweg begaanbaar": [23, 147, 0, 140],
          "Begaanbaar voor calamiteitenverkeer": [255, 206, 0, 140],
          "Hoofdweg begaanbaar voor calamiteitenverkeer": [255, 206, 0, 140],
          "Onbegaanbaar": [227, 28, 26, 140],
          "Hoofdweg onbegaanbaar": [227, 28, 26, 140],
        },
        default: [60, 60, 200, 140],
      },
    },
    {
      id: "wolk-stroombanen",
      name: "Wateroverlast Stroombanen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Wolk/MapServer/1",
      source: "Gemeente Zwolle GIS",
      description: "Potentiële wateraccumulatie stroombanen bij pluviale overlast",
      category: "veiligheid",
      color: [30, 80, 200, 140],
      icon: "Droplets",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Wolk", 1, "MapServer", 2000, full),
    },

    // ═══════════════════════════════════════
    // NOISE MAPS
    // ═══════════════════════════════════════
    {
      id: "geluid-wegverkeer",
      name: "Geluid Wegverkeer",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Geluidsbelastingkaart/MapServer/8",
      source: "Gemeente Zwolle GIS",
      description: "Geluidsbelasting door wegverkeer (Lden in dB)",
      category: "omgevingsfactoren",
      color: [255, 100, 100, 100],
      icon: "Volume2",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Geluidsbelastingkaart", 8, "MapServer", 2000, full),
      colorMap: {
        property: "LEGENDA",
        values: {
          "45 - 50 dB": [104, 179, 43, 100],
          "50 - 55 dB": [181, 204, 4, 100],
          "55 - 60 dB": [242, 238, 0, 100],
          "60 - 65 dB": [240, 124, 36, 100],
          "65 - 70 dB": [227, 27, 31, 100],
          "70 dB of meer": [153, 72, 149, 100],
        },
        default: [255, 100, 100, 100],
      },
    },
    {
      id: "geluid-treinverkeer",
      name: "Geluid Treinverkeer",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Geluidsbelastingkaart/MapServer/5",
      source: "Gemeente Zwolle GIS",
      description: "Geluidsbelasting door treinverkeer (Lden in dB)",
      category: "omgevingsfactoren",
      color: [200, 80, 200, 100],
      icon: "Volume2",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Geluidsbelastingkaart", 5, "MapServer", 2000, full),
      colorMap: {
        property: "LEGENDA",
        values: {
          "45 - 50 dB": [104, 179, 43, 100],
          "50 - 55 dB": [181, 204, 4, 100],
          "55 - 60 dB": [242, 238, 0, 100],
          "60 - 65 dB": [240, 124, 36, 100],
          "65 - 70 dB": [227, 27, 31, 100],
          "70 dB of meer": [153, 72, 149, 100],
        },
        default: [200, 80, 200, 100],
      },
    },
    {
      id: "geluid-industrie",
      name: "Geluid Industrie",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Geluidsbelastingkaart/MapServer/1",
      source: "Gemeente Zwolle GIS",
      description: "Geluidsbelasting door industrielawaai (Lden in dB)",
      category: "omgevingsfactoren",
      color: [200, 160, 60, 100],
      icon: "Volume2",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Geluidsbelastingkaart", 1, "MapServer", 2000, full),
      colorMap: {
        property: "LEGENDA",
        values: {
          "45 - 50 dB": [104, 179, 43, 100],
          "50 - 55 dB": [181, 204, 4, 100],
          "55 - 60 dB": [242, 238, 0, 100],
          "60 - 65 dB": [240, 124, 36, 100],
          "65 - 70 dB": [227, 27, 31, 100],
          "70 dB of meer": [153, 72, 149, 100],
        },
        default: [200, 160, 60, 100],
      },
    },

    // ═══════════════════════════════════════
    // SOCIAL TEAMS, ACCESSIBILITY, MUNICIPAL PROJECTS
    // ═══════════════════════════════════════
    {
      id: "swt-locaties",
      name: "Sociaal Wijkteam Locaties",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/SWT/MapServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Locaties van sociale wijkteams",
      category: "sociaal-economisch",
      color: [100, 200, 180, 200],
      icon: "Users",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 7,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("SWT", 0, "MapServer", 2000, full),
    },
    {
      id: "swt-gebieden",
      name: "Sociaal Wijkteam Gebieden",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/SWT/MapServer/1",
      source: "Gemeente Zwolle GIS",
      description: "Werkgebieden van sociale wijkteams",
      category: "sociaal-economisch",
      color: [100, 200, 180, 60],
      icon: "Users",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("SWT", 1, "MapServer", 2000, full),
    },
    {
      id: "toegankelijkheid",
      name: "Toegankelijkheidsmeldingen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Toegankelijkheid_publiek/MapServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Meldingen over toegankelijkheidsproblemen door burgers",
      category: "gezondheid-norm",
      color: [255, 180, 0, 200],
      icon: "Accessibility",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 5,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Toegankelijkheid_publiek", 0, "MapServer", 2000, full),
    },
    {
      id: "gemeentelijke-projecten",
      name: "Gemeentelijke Projecten",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/VP/MapServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Lopende en geplande gemeentelijke projecten",
      category: "gebouwen-infra",
      color: [120, 100, 255, 180],
      icon: "Flag",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 6,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("VP", 0, "MapServer", 2000, full),
    },

    // ═══════════════════════════════════════
    // BOR Kap & Herplant
    // ═══════════════════════════════════════
    {
      id: "bor-herplant",
      name: "Herplant Bomen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/BOR_kap_herplant_openbaar/MapServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Herplantlocaties voor gekapte bomen",
      category: "groen-ecologie",
      color: [60, 200, 60, 180],
      icon: "TreePine",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 4,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("BOR_kap_herplant_openbaar", 0, "MapServer", 2000, full),
    },
    {
      id: "bor-kap",
      name: "Kap Uitvoering",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/BOR_kap_herplant_openbaar/MapServer/1",
      source: "Gemeente Zwolle GIS",
      description: "Locaties waar bomen gekapt worden",
      category: "groen-ecologie",
      color: [200, 60, 60, 180],
      icon: "TreePine",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 4,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("BOR_kap_herplant_openbaar", 1, "MapServer", 2000, full),
    },

    // ═══════════════════════════════════════
    // Wildplukkaart, Hessenpoort, BomenSnoei, Inspectiebomen
    // ═══════════════════════════════════════
    {
      id: "wildplukkaart",
      name: "Wildplukkaart Bomen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Eetbaar_groen_Wildplukkaart/MapServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Bomen geschikt voor wildplukken (noten, fruit, etc.)",
      category: "groen-ecologie",
      color: [180, 120, 40, 200],
      icon: "Apple",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 4,
      defaultLimit: 2000,
      fetchData: async (full) => {
        const data = await fzg("Eetbaar_groen_Wildplukkaart", 0, "MapServer", 2000, full);
        return {
          ...data,
          features: data.features
            .map((f) => {
              if (f.geometry) return f;
              const lng = parseFloat(String(f.properties?.X_WGS84));
              const lat = parseFloat(String(f.properties?.Y_WGS84));
              if (isNaN(lng) || isNaN(lat)) return null;
              return { ...f, geometry: { type: "Point" as const, coordinates: [lng, lat] } };
            })
            .filter((f): f is GeoJSON.Feature => f !== null),
        };
      },
    },
    {
      id: "hessenpoort-kavels",
      name: "Hessenpoort Kavels",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Hessenpoort/MapServer/3",
      source: "Gemeente Zwolle GIS",
      description: "Beschikbare bedrijfskavels op Hessenpoort",
      category: "gebouwen-infra",
      color: [100, 120, 200, 120],
      icon: "Store",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Hessenpoort", 3, "MapServer", 2000, full),
    },
    {
      id: "bomen-snoei",
      name: "Bomensnoei",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/BomenSnoei/MapServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Locaties waar bomen gesnoeid worden",
      category: "groen-ecologie",
      color: [80, 160, 40, 180],
      icon: "TreePine",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 3,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("BomenSnoei", 0, "MapServer", 2000, full),
    },
    {
      id: "inspectiebomen",
      name: "Inspectiebomen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Inspectiebomen/MapServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Bomen met veiligheidsinspectie",
      category: "groen-ecologie",
      color: [200, 160, 40, 180],
      icon: "Search",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 3,
      fetchData: async () =>
        fetchGeoJSON(
          `${ZWOLLE_GIS}/Inspectiebomen/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=geojson`
        ),
    },
    {
      id: "tor-stadsdelen",
      name: "TOR Incidenten (Stadsdelen)",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/TOR_stadsdelen/FeatureServer/0",
      source: "Gemeente Zwolle GIS",
      description: "Stadsdeelgrenzen gekoppeld aan TOR-incidentmeldingen",
      category: "veiligheid",
      color: [255, 100, 80, 60],
      icon: "Map",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("TOR_stadsdelen", 0, "FeatureServer", 2000, full),
    },

    // ═══════════════════════════════════════
    // ENEXIS ENERGY GRID
    // ═══════════════════════════════════════
    {
      id: "enexis-gas-hoofdleiding",
      name: "Enexis Gas Hoofdleidingen",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Energie_in_Beeld_Enexis_Assets/MapServer/3",
      source: "Gemeente Zwolle GIS / Enexis",
      description: "Gasleidingen (hoofdleidingen) Enexis netwerk",
      category: "energie",
      color: [255, 200, 0, 140],
      icon: "Flame",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Energie_in_Beeld_Enexis_Assets", 3, "MapServer", 2000, full),
    },
    {
      id: "enexis-elektra-kabel",
      name: "Enexis Elektriciteitskabels",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Energie_in_Beeld_Enexis_Assets/MapServer/7",
      source: "Gemeente Zwolle GIS / Enexis",
      description: "Elektriciteitskabels Enexis netwerk",
      category: "energie",
      color: [255, 80, 0, 140],
      icon: "Zap",
      visible: false,
      loading: false,
      filled: false,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Energie_in_Beeld_Enexis_Assets", 7, "MapServer", 2000, full),
    },
    {
      id: "enexis-gas-stations",
      name: "Enexis Gasstations",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Energie_in_Beeld_Enexis_Assets/MapServer/1",
      source: "Gemeente Zwolle GIS / Enexis",
      description: "Technische gebouwen gas (hoge druk)",
      category: "energie",
      color: [255, 220, 60, 200],
      icon: "Flame",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 5,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Energie_in_Beeld_Enexis_Assets", 1, "MapServer", 2000, full),
    },
    {
      id: "enexis-elektra-stations",
      name: "Enexis Elektrastations",
      endpoint: "gisservices.zwolle.nl/ArcGIS/rest/services/Energie_in_Beeld_Enexis_Assets/MapServer/5",
      source: "Gemeente Zwolle GIS / Enexis",
      description: "Technische gebouwen elektra (middenspanning)",
      category: "energie",
      color: [255, 120, 0, 200],
      icon: "Zap",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 4,
      defaultLimit: 2000,
      fetchData: async (full) => fzg("Energie_in_Beeld_Enexis_Assets", 5, "MapServer", 2000, full),
    },

    // ─── Eigendom & grondregistratie ─────────────────────────────────────
    // Lokale gemeente-asset: gisservices.zwolle.nl exposes geen publiek
    // Eigendom- of Erfpacht-service — stubs tot Zwolle een open laag publiceert.
    {
      id: "gemeentelijk-eigendom",
      name: "Gemeentelijk Eigendom",
      endpoint: "—",
      source: "—",
      description:
        "Percelen in eigendom van de gemeente Zwolle — niet beschikbaar als open dataset",
      category: "gebouwen-infra",
      color: [180, 80, 60, 100],
      icon: "Building",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      availability: "stub",
      isNew: true,
      fetchData: fetchEmpty,
    },
    {
      id: "erfpacht",
      name: "Erfpachtpercelen",
      endpoint: "—",
      source: "—",
      description:
        "Erfpachtpercelen — gemeentelijk uitgegeven (niet beschikbaar als open dataset)",
      category: "gebouwen-infra",
      color: [200, 120, 40, 100],
      icon: "Hourglass",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      availability: "stub",
      isNew: true,
      fetchData: fetchEmpty,
    },
  ];
}
