/**
 * Gelderland provincial layers — shared by all Gelderland municipalities.
 *
 * Source: Geoportaal Gelderland (geoportaal.gelderland.nl)
 * Extracted from cities/apeldoorn.ts — layer IDs are unchanged.
 */

import type { CityConfig } from "../../cities";
import type { DataSource } from "../types";
import { fetchArcGISQuery } from "../fetchers";

const GLD_GIS = "https://geoportaal.gelderland.nl/gisserver/rest/services";

function gld(
  service: string,
  layerId: number,
  serverType: "FeatureServer" | "MapServer" = "MapServer",
  maxFeatures = 2000,
  full = false
) {
  return fetchArcGISQuery(GLD_GIS, service, layerId, serverType, maxFeatures, full);
}

export function buildGelderlandLayers(_city: CityConfig): DataSource[] {
  return [
    {
      id: "gld-luchtkwaliteit-pm10",
      name: "Fijnstof PM10 per buurt",
      endpoint: "geoportaal.gelderland.nl/gisserver/rest/services/Milieu/Milieu/MapServer/17",
      source: "Geoportaal Gelderland",
      description: "Fijnstof (PM10) immissie-concentraties per buurt in Gelderland",
      category: "omgevingsfactoren",
      color: [200, 100, 60, 100],
      icon: "Volume2",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 500,
      isNew: true,
      fetchData: async (full) => gld("Milieu/Milieu", 17, "MapServer", 500, full),
    },
    {
      id: "gld-luchtkwaliteit-pm25",
      name: "Fijnstof PM2.5 per buurt",
      endpoint: "geoportaal.gelderland.nl/gisserver/rest/services/Milieu/Milieu/MapServer/18",
      source: "Geoportaal Gelderland",
      description: "Fijnstof (PM2.5) immissie-concentraties per buurt in Gelderland",
      category: "omgevingsfactoren",
      color: [180, 80, 40, 100],
      icon: "Volume2",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 500,
      isNew: true,
      fetchData: async (full) => gld("Milieu/Milieu", 18, "MapServer", 500, full),
    },
    {
      id: "gld-luchtkwaliteit-no2",
      name: "Stikstofdioxide NO₂ per buurt",
      endpoint: "geoportaal.gelderland.nl/gisserver/rest/services/Milieu/Milieu/MapServer/16",
      source: "Geoportaal Gelderland",
      description: "Stikstofdioxide (NO₂) immissie-concentraties per buurt",
      category: "omgevingsfactoren",
      color: [180, 60, 180, 100],
      icon: "Volume2",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 500,
      isNew: true,
      fetchData: async (full) => gld("Milieu/Milieu", 16, "MapServer", 500, full),
    },
    {
      id: "gld-zonneparken",
      name: "Zonneparken (provincie)",
      endpoint: "geoportaal.gelderland.nl/gisserver/rest/services/Milieu/Milieu/MapServer/26",
      source: "Geoportaal Gelderland",
      description: "Geregistreerde zonneparken in Gelderland",
      category: "energie",
      color: [255, 200, 0, 200],
      icon: "Zap",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 500,
      isNew: true,
      fetchData: async (full) => gld("Milieu/Milieu", 26, "MapServer", 500, full),
    },
    {
      id: "gld-stortplaatsen",
      name: "Stortplaatsen (Wm)",
      endpoint: "geoportaal.gelderland.nl/gisserver/rest/services/Milieu/Milieu/MapServer/8",
      source: "Geoportaal Gelderland",
      description: "Stortplaatsen onder Wet Milieubeheer-nazorg",
      category: "bodem-ondergrond",
      color: [140, 80, 40, 200],
      icon: "Trash2",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 5,
      defaultLimit: 200,
      isNew: true,
      fetchData: async (full) => gld("Milieu/Milieu", 8, "MapServer", 200, full),
    },
    {
      id: "gld-bodem-baggerdepots",
      name: "Baggerdepots",
      endpoint: "geoportaal.gelderland.nl/gisserver/rest/services/Milieu/Milieu/MapServer/10",
      source: "Geoportaal Gelderland",
      description: "Bodem baggerdepots onder Wet Milieubeheer",
      category: "bodem-ondergrond",
      color: [120, 90, 50, 180],
      icon: "Droplets",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 5,
      defaultLimit: 200,
      isNew: true,
      fetchData: async (full) => gld("Milieu/Milieu", 10, "MapServer", 200, full),
    },
    {
      id: "gld-recreatiezonering-veluwe",
      name: "Recreatiezonering Veluwe",
      endpoint: "geoportaal.gelderland.nl/gisserver/rest/services/Natuur/Natuur/MapServer/16",
      source: "Geoportaal Gelderland",
      description: "Recreatiezonering op de Veluwe — toegang en kwetsbaarheid",
      category: "groen-ecologie",
      color: [40, 160, 80, 100],
      icon: "TreePine",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 2,
      defaultLimit: 500,
      isNew: true,
      fetchData: async (full) => gld("Natuur/Natuur", 16, "MapServer", 500, full),
    },
    {
      id: "gld-faunapassages",
      name: "Faunapassages",
      endpoint: "geoportaal.gelderland.nl/gisserver/rest/services/Natuur/Natuur/MapServer/12",
      source: "Geoportaal Gelderland",
      description: "Faunapassages voor wildlife-doorgang",
      category: "groen-ecologie",
      color: [40, 200, 100, 200],
      icon: "TreePine",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 5,
      defaultLimit: 500,
      isNew: true,
      fetchData: async (full) => gld("Natuur/Natuur", 12, "MapServer", 500, full),
    },
    {
      id: "gld-groen-blauwe-dooradering",
      name: "Groen-blauwe dooradering",
      endpoint: "geoportaal.gelderland.nl/gisserver/rest/services/Natuur/Natuur/MapServer/13",
      source: "Geoportaal Gelderland",
      description: "Verbindingen voor flora & fauna in het landschap",
      category: "groen-ecologie",
      color: [80, 200, 120, 80],
      icon: "Leaf",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 500,
      isNew: true,
      fetchData: async (full) => gld("Natuur/Natuur", 13, "MapServer", 500, full),
    },
    {
      id: "gld-grondwaterkwaliteit",
      name: "Grondwaterkwaliteit (KRW)",
      endpoint: "geoportaal.gelderland.nl/gisserver/rest/services/Water/Water/MapServer/0",
      source: "Geoportaal Gelderland",
      description: "Meetnet grondwaterkwaliteit voor de Kaderrichtlijn Water",
      category: "bodem-ondergrond",
      color: [40, 120, 200, 200],
      icon: "Droplets",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 4,
      defaultLimit: 500,
      isNew: true,
      fetchData: async (full) => gld("Water/Water", 0, "MapServer", 500, full),
    },
    {
      id: "gld-grondwaterlichamen",
      name: "Grondwaterlichamen (KRW)",
      endpoint: "geoportaal.gelderland.nl/gisserver/rest/services/Water/Water/MapServer/2",
      source: "Geoportaal Gelderland",
      description: "Grondwaterlichamen voor de Kaderrichtlijn Water",
      category: "bodem-ondergrond",
      color: [60, 100, 200, 60],
      icon: "Droplets",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 200,
      isNew: true,
      fetchData: async (full) => gld("Water/Water", 2, "MapServer", 200, full),
    },
    {
      id: "gld-uiterwaarden",
      name: "Uiterwaarden",
      endpoint: "geoportaal.gelderland.nl/gisserver/rest/services/Water/Water/MapServer/6",
      source: "Geoportaal Gelderland",
      description: "Uiterwaarden van de IJssel en andere Gelderse rivieren",
      category: "bodem-ondergrond",
      color: [80, 150, 220, 100],
      icon: "Waves",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 500,
      isNew: true,
      fetchData: async (full) => gld("Water/Water", 6, "MapServer", 500, full),
    },
    {
      id: "gld-bebouwde-kommen",
      name: "Bebouwde Kommen (Gelderland)",
      endpoint: "geoportaal.gelderland.nl/gisserver/rest/services/Topografie/Topografie/MapServer/1",
      source: "Geoportaal Gelderland",
      description: "Bebouwde kommen in Gelderland",
      category: "gebouwen-infra",
      color: [200, 160, 100, 80],
      icon: "Map",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 500,
      isNew: true,
      fetchData: async (full) => gld("Topografie/Topografie", 1, "MapServer", 500, full),
    },
  ];
}
