/**
 * Utrecht provincial layers — discovered 2026-05-08.
 *
 * Source: gis.provincie-utrecht.nl ArcGIS REST (v11.5)
 *   - https://gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer
 *   - https://gis.provincie-utrecht.nl/arcgis/rest/services/WFS_IKN/MapServer
 *   - https://gis.provincie-utrecht.nl/arcgis/rest/services/m01_2_bodem/MapServer
 *
 * Auto-generated by /promote-city; review before commit.
 * All layers use MapServer with query support (GeoJSON output via f=geojson).
 */

import type { CityConfig } from "../../cities";
import type { DataSource } from "../types";
import { fetchGeoJSON } from "../fetchers";

const GIS_BASE = "https://gis.provincie-utrecht.nl/arcgis/rest/services";

function fetchUtrechtMapServer(
  service: string,
  layerId: number,
  city: CityConfig,
  maxFeatures = 2000,
  full = false
): Promise<GeoJSON.FeatureCollection> {
  const count = full ? 50000 : maxFeatures;
  const [lonMin, latMin, lonMax, latMax] = city.bbox;
  const url =
    `${GIS_BASE}/${service}/MapServer/${layerId}/query` +
    `?where=1%3D1` +
    `&geometry=${lonMin}%2C${latMin}%2C${lonMax}%2C${latMax}` +
    `&geometryType=esriGeometryEnvelope` +
    `&inSR=4326` +
    `&spatialRel=esriSpatialRelIntersects` +
    `&outFields=*` +
    `&outSR=4326` +
    `&f=geojson` +
    `&resultRecordCount=${count}`;
  return fetchGeoJSON(url);
}

export function buildUtrechtLayers(city: CityConfig): DataSource[] {
  return [
    // ─── BODEM & ONDERGROND ───────────────────────────────────────────────────
    {
      id: "ut-prov-geomorfologie",
      name: "Geomorfologische Kaart 1:50.000",
      description:
        "Geomorfologische eenheden (BRO) op schaal 1:50.000 voor Utrecht — dekzandruggen, stuifzanden, riviervlaktes e.d.",
      source: "Provincie Utrecht GIS",
      sourceUrl:
        "https://gis.provincie-utrecht.nl/arcgis/rest/services/m01_2_bodem/MapServer",
      endpoint:
        "gis.provincie-utrecht.nl/arcgis/rest/services/m01_2_bodem/MapServer/0",
      category: "bodem-ondergrond",
      color: [160, 110, 60, 160],
      icon: "Layers",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: (full) =>
        fetchUtrechtMapServer("m01_2_bodem", 0, city, 2000, full),
    },
    {
      id: "ut-prov-bodemkwaliteit",
      name: "Bodemkwaliteitskaart Utrecht",
      description:
        "Bodemkwaliteitszones conform de Utrechtse bodemkwaliteitskaart — basis voor grondverzet.",
      source: "Provincie Utrecht GIS",
      sourceUrl:
        "https://gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer",
      endpoint:
        "gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer/37",
      category: "bodem-ondergrond",
      color: [180, 140, 80, 150],
      icon: "Layers",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 500,
      fetchData: (full) =>
        fetchUtrechtMapServer("Tygron_Basisdata", 37, city, 500, full),
    },
    {
      id: "ut-prov-wko-grondwater",
      name: "WKO Grondwateronttrekkingen",
      description:
        "Vergunde warmte-koude-opslag (WKO) grondwateronttrekkingspunten in Utrecht — locatie, pakket, debiet.",
      source: "Provincie Utrecht GIS",
      sourceUrl:
        "https://gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer",
      endpoint:
        "gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer/41",
      category: "bodem-ondergrond",
      color: [0, 160, 210, 220],
      icon: "Droplets",
      visible: false,
      loading: false,
      pointType: "scatterplot",
      radius: 6,
      defaultLimit: 500,
      fetchData: (full) =>
        fetchUtrechtMapServer("Tygron_Basisdata", 41, city, 500, full),
    },
    // ─── GROEN & ECOLOGIE ─────────────────────────────────────────────────────
    {
      id: "ut-prov-nnn",
      name: "Natuurnetwerk Nederland (NNN)",
      description:
        "Gebieden aangewezen als Natuurnetwerk Nederland (NNN) in de Omgevingsverordening Utrecht.",
      source: "Provincie Utrecht GIS",
      sourceUrl:
        "https://gis.provincie-utrecht.nl/arcgis/rest/services/WFS_IKN/MapServer",
      endpoint:
        "gis.provincie-utrecht.nl/arcgis/rest/services/WFS_IKN/MapServer/10",
      category: "groen-ecologie",
      color: [34, 139, 34, 160],
      icon: "TreePine",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 1000,
      fetchData: (full) =>
        fetchUtrechtMapServer("WFS_IKN", 10, city, 1000, full),
    },
    {
      id: "ut-prov-groene-contour",
      name: "Groene Contour (NNN-overgangszone)",
      description:
        "Overgangszones rondom het Natuurnetwerk Nederland — toekomstige natuur en verbindingszones (Groene Contour).",
      source: "Provincie Utrecht GIS",
      sourceUrl:
        "https://gis.provincie-utrecht.nl/arcgis/rest/services/WFS_IKN/MapServer",
      endpoint:
        "gis.provincie-utrecht.nl/arcgis/rest/services/WFS_IKN/MapServer/11",
      category: "groen-ecologie",
      color: [100, 180, 80, 140],
      icon: "TreePine",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 1000,
      fetchData: (full) =>
        fetchUtrechtMapServer("WFS_IKN", 11, city, 1000, full),
    },
    {
      id: "ut-prov-tygron-nnn",
      name: "Natuur Netwerk (Tygron Basisdata)",
      description:
        "Natuur Netwerk Nederland-vlakken uit de Tygron Basisdata basiskaart voor de provincie Utrecht.",
      source: "Provincie Utrecht GIS",
      sourceUrl:
        "https://gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer",
      endpoint:
        "gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer/13",
      category: "groen-ecologie",
      color: [20, 120, 20, 150],
      icon: "TreePine",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 1000,
      fetchData: (full) =>
        fetchUtrechtMapServer("Tygron_Basisdata", 13, city, 1000, full),
    },
    // ─── OMGEVINGSFACTOREN ────────────────────────────────────────────────────
    {
      id: "ut-prov-geluid-cumulatief",
      name: "Geluidbelasting Cumulatief (WHO)",
      description:
        "Gecumuleerde geluidbelastingklassen (Lden) conform WHO-normen voor de provincie Utrecht.",
      source: "Provincie Utrecht GIS",
      sourceUrl:
        "https://gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer",
      endpoint:
        "gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer/4",
      category: "omgevingsfactoren",
      color: [255, 80, 0, 160],
      icon: "Volume2",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 2000,
      fetchData: (full) =>
        fetchUtrechtMapServer("Tygron_Basisdata", 4, city, 2000, full),
    },
    {
      id: "ut-prov-no2",
      name: "Luchtkwaliteit NO₂",
      description:
        "Stikstofdioxide (NO₂) concentratieklassen in de provincie Utrecht (actuele meting).",
      source: "Provincie Utrecht GIS",
      sourceUrl:
        "https://gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer",
      endpoint:
        "gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer/28",
      category: "omgevingsfactoren",
      color: [220, 60, 60, 160],
      icon: "Wind",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 500,
      fetchData: (full) =>
        fetchUtrechtMapServer("Tygron_Basisdata", 28, city, 500, full),
    },
    {
      id: "ut-prov-pm10",
      name: "Luchtkwaliteit PM10",
      description:
        "Fijnstof PM10 concentratieklassen in de provincie Utrecht (actuele meting).",
      source: "Provincie Utrecht GIS",
      sourceUrl:
        "https://gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer",
      endpoint:
        "gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer/29",
      category: "omgevingsfactoren",
      color: [200, 100, 20, 150],
      icon: "Wind",
      visible: false,
      loading: false,
      filled: true,
      stroked: false,
      defaultLimit: 500,
      fetchData: (full) =>
        fetchUtrechtMapServer("Tygron_Basisdata", 29, city, 500, full),
    },
    // ─── VEILIGHEID ───────────────────────────────────────────────────────────
    {
      id: "ut-prov-overstroombaar",
      name: "Overstromingsgevoelige Gebieden",
      description:
        "Vlakken die als overstroombaar zijn aangemerkt in de provincie Utrecht (waterkeringszones).",
      source: "Provincie Utrecht GIS",
      sourceUrl:
        "https://gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer",
      endpoint:
        "gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer/7",
      category: "veiligheid",
      color: [0, 120, 220, 140],
      icon: "Waves",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 200,
      fetchData: (full) =>
        fetchUtrechtMapServer("Tygron_Basisdata", 7, city, 200, full),
    },
    // ─── MOBILITEITSDIENSTEN ──────────────────────────────────────────────────
    {
      id: "ut-prov-bushalte-buffer",
      name: "Afstand tot Bushalte (400 m zones)",
      description:
        "Buffergebieden op 400 m rondom bushaltes in de provincie Utrecht — indicatie OV-bereikbaarheid.",
      source: "Provincie Utrecht GIS",
      sourceUrl:
        "https://gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer",
      endpoint:
        "gis.provincie-utrecht.nl/arcgis/rest/services/Tygron_Basisdata/MapServer/44",
      category: "mobiliteitsdiensten",
      color: [80, 150, 220, 130],
      icon: "Bus",
      visible: false,
      loading: false,
      filled: true,
      stroked: true,
      lineWidth: 1,
      defaultLimit: 2000,
      fetchData: (full) =>
        fetchUtrechtMapServer("Tygron_Basisdata", 44, city, 2000, full),
    },
  ];
}
